### ISSUE TITLE
Undefined symbols for architecture i386

### ISSUE THREAD

**Issue by iSpartak** [bfeher/BFRadialWaveHUD#1]
Hi Bence,

I'm getting below error when trying to use BFRadialWaveHUD

Undefined symbols for architecture i386:
  "_BFRadialWaveHUD_DefaultCircleStrokeWidth", referenced from:
      -[ViewController startScan] in ViewController.o
  "_BFRadialWaveHUD_DefaultNumberOfCircles", referenced from:
      -[ViewController startScan] in ViewController.o
  "_OBJC_CLASS_$_BFRadialWaveHUD", referenced from:
      objc-class-ref in ViewController.o
ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)

  "_BFRadialWaveHUD_DefaultCircleStrokeWidth", referenced from:

```
  -[ViewController startScan] in ViewController.o
```

  "_BFRadialWaveHUD_DefaultNumberOfCircles", referenced from:

```
  -[ViewController startScan] in ViewController.o
```

  "_OBJC_CLASS_$_BFRadialWaveHUD", referenced from:

```
  objc-class-ref in ViewController.o
```

ld: symbol(s) not found for architecture i386

clang: error: linker command failed with exit code 1 (use -v to see invocation)

I did not install it throw pod but just copied Categories, Classes and Resources folder.

Any idea what can be wrong?

**Comment by bfeher** [comment]
Hi @iSpartak! Thanks for submitting this issue!

I can't really be sure what's going on with the linker issues, but I am certain that you are missing some important files. 

BFRadialWaveHUD uses [BFRadialWaveView](https://github.com/bfeher/BFRadialWaveView) and [BFPaperColors](https://github.com/bfeher/BFPaperColors) which you would have to copy over as well.

My best advice is to install BFRadialWaveHUD via cocoapods and see if the error is still there. If you really don't want to use cocoapods, I implore that you should give it a try, but you can always still try manually copying the class files from the 2 other pods required by this one.

Let me know how it goes please :)

**Comment by iSpartak** [comment]
Thank you, Bence!

Yes, I've installed it via cocoapods and all works as a charming :)

Another but quick question, is it possible to change the speed somehow? 

PS: Thanks for this briliant component!

**Comment by bfeher** [comment]
I'm glad its working!

There is a private property in `BFPaperRadialWaveView.m`:
`self.animationDuration = 1.f;`

You can set that to speed up or slow down the animation, but its not global. The checkmark drawing and progress won't be affected. I don't have a public way to set the speed yet :(

**Comment by bfeher** [comment]
I'm going to close this issue and open a new Feature Request for the animation duration. Thank you.
