### ISSUE TITLE
Feature request - provide completion block for dismissal

### ISSUE THREAD

**Issue by ConfusedVorlon** [bfeher/BFRadialWaveHUD#2]
Firstly - thanks for a great component!

I'm using showWithMessage and tapToDismiss.
It would be great to set a completion block on the TapToDismiss

At the moment, I'm subclassing and overriding dismiss - but that's a rubbish hack.

I'd suggest just exposing and calling:

@property (nonatomic, copy) void (^tapToDismissCompletionBlock)(BOOL finished);

**Comment by bfeher** [comment]
Hi @ConfusedVorlon! Thanks for using and supporting this control!

I've pushed a new version + pod, 1.5.1, which adds the following public property:

``` objective-c
/** Block to run after dismissal via tap. */
@property (nonatomic, copy) void (^tapToDismissCompletionBlock)(BOOL finished);
```

Thanks again for your suggestion. Let me know if this isn't what you had in mind or if you have any further issues/suggestions :)

**Comment by ConfusedVorlon** [comment]
that's perfect - thank you.
