### ISSUE TITLE
Strange behavior in HUD as a property

### ISSUE THREAD

**Issue by xico42** [bfeher/BFRadialWaveHUD#4]
In the example provided, the hud is initialized every time it is used. If make a property, initialize it in
the viewDidLoad, after the first dismiss, the hud presents strange behavior. Like if the radius, or
strokeWidth changed.

_The first call:_
![first](https://cloud.githubusercontent.com/assets/6249736/7573441/f91f5cd8-f7fb-11e4-8f49-179ece1c3ba6.png)

_After dismiss:_
![dismiss](https://cloud.githubusercontent.com/assets/6249736/7573452/023422ea-f7fc-11e4-98e8-1c3f1f8fc40e.png)

**Comment by bfeher** [comment]
Hi fco-edno!
This should be fixed in the latest version, 1.5.2 which was just released yesterday :)
Please update and let me know if it is still behaving this way. Thanks!

**Comment by xico42** [comment]
It works like a charm :). Sorry for that.

**Comment by bfeher** [comment]
No problem; thanks for using this control!
