### ISSUE TITLE
Cocoapods - wrong versioning

### ISSUE THREAD

**Issue by natalia-osa** [bfeher/BFRadialWaveHUD#8]
Hi,

Personally, I think the way with pointing to HEAD in .podspec isn't the best idea. Do notice, that we can use the library in production code. Now, our tester performs all the manual testing, we're ready to release. But we perform release on our CI. It downloads the "new and untested" version of the hud and we release broken app to the AppStore. Of course I wish you that the library won't ever be broken, but it may happen.

Another case is that something changes. We want to check out the old version of your project and we're unable to do so.

Because of these things maybe it would be better to version also in CocoaPods?

Also, I've installed your project via CocoaPods:
Command line:
`$ pod install`
`Installing BFRadialWaveHUD (1.5.3)`

Podfile:
`pod 'BFRadialWaveHUD', '~> 1.5.3'`

However on my `hud` object, I can call only `showError`, no way to `showErrorWith...`, so I suspect in fact it isn't the newest version. It might be because your library was cached on that version and now doesn't update itself, because you don't update the .podspec - or at least I guess so.

Thanks for the support.

**Comment by bfeher** [comment]
Hi @natalia-osa !

I must admit that I chose to point to HEAD out of pure laziness. I was tired of updating this control's Podfile every time I made a slight change to BFRadialWaveView. I understand your argument and would like your input on how I should write the Podfile. Should I just do:

`pod 'BFRadialWaveView'`

or use one of the special operators listed on the [cocoapods documentation](https://guides.cocoapods.org/syntax/podfile.html#pod)?

In my experience, no operator is necessary, and if you want the newest version you can always run a `pod outdated` followed by a `pod update`.

Anyways, I will await your feedback and then update this pod accordingly as soon as we agree :)

For your second point, I'm sorry but I cannot duplicate that. I created a new project, used the same Podfile and commands from your post above:
![screen shot 2016-01-15 at 9 00 02 am](https://cloud.githubusercontent.com/assets/3466708/12341652/84441500-bb66-11e5-942b-656259da26dc.png)

But I was able to use all of the newest functions:
![screen shot 2016-01-15 at 8 46 19 am](https://cloud.githubusercontent.com/assets/3466708/12341578/10d7853e-bb66-11e5-8cbd-aa3056b4983d.png)

I'm not sure what would be causing your issue, sorry :(

**Comment by natalia-osa** [comment]
Hi @bfeher, nice to meet you.

Hmm. I've checked the CocoaPods spec repo, my local .cocoapods folder, everywhere it seems that the version `1.5.3` exists. Thus, I also have no idea why an older version is installed.

Anyway, coming back to the topic of versioning. This is always a dilemma. There are two options: 
- either you keep it as it is, with the newest version (solution A), 
- or you point to a specific tag (solution B).

Solution B has disadvantages, which were shown in case of eg `AFNetworking` and `RestKit`, where `RestKit` forced people to use old version of `AFNetworking` (well it was possible to have both of the versions, but it demanded to change the source project and was hard to do). If you used newer version of `AFNetworking` in your project and wanted to implement `RestKit` you had to revert to older version everything you've written so far. I had finished with the same solution as your in my pods, where I've been pointing to the newest version - otherwise, often different pods were pointing to a different version of subspec, importing such thing in a project is invalid. But you had strct control under the version, it was more convenient to test. I'm sorry to repeat if you already knew that - it's better to say more than not enough.
Solution A is faster to implement, but in edge cases you can finish with not working project - `HUD` would require a method from `View`, which was removed in newest version. It's worse in terms of testing. Also, you have to update dependent project.

So it's your decision which way you want to have here =). Personally I think not many people would like to have a different version of `View` than it is in `HUD`, so probably I'd go with specific tag. However that's just my opinion. I've opened the issue due to that problem where I can't download the newest code version.

As I read you statement: "The podfile always points to :HEAD so running the above command will ensure you have the latest version of `BFRadialWaveView`" I thought you did it in a different way. I thought you used something like `:head`. The way you did it is pointing to the newest version of `BFRadialWaveView` which is pushed to the cocoapods repo, not to `HEAD`... or at least I always thought it is working like this. I may be wrong (but couldn't find any reference according to this topic right now), if so please point it out. This way is exactly the situation with solution A, and it is a proper solution. Mea culpa I didn't check what you have in your podspec. Anyway, maybe you could edit this part of Readme if I'm right, because it's misleading.

Finally, I don't understand why you wrote about Podfile? We're talking about Podspec now, where you've declared:

```
"dependencies": {
    "UIColor+BFPaperColors": [],
    "BFRadialWaveView": []
  }
```

**Comment by bfeher** [comment]
Hello again!

Thank you for your response. I think I will go ahead and use solution A with the addition of the '~>' operator to hopefully allow some flexibility. The current Podfile has this line:
`pod 'UIColor+BFPaperColors', :head`
which according to my interpretation of the [cocoapods documentation](https://guides.cocoapods.org/using/the-podfile.html) (search for "head"), should point to the head of the repo. That being said, I could be totally wrong. Anyways, this is going to be replaced with the next release.

As far as:

```
"dependencies": {
    "UIColor+BFPaperColors": [],
    "BFRadialWaveView": []
  }
```

Where do you see this? In the file [BFRadialWaveHUD.podspec](BFRadialWaveHUD/BFRadialWaveHUD.podspec), I see this:

```
s.dependency   'UIColor+BFPaperColors'
s.dependency   'BFRadialWaveView'
```

This lists those 2 pods as [dependancies](https://guides.cocoapods.org/syntax/podspec.html#dependency) to this pod.
Anyway, hopefully once I refactor how the pods interact with each other, simply removing and re-adding BFRadialWaveHUD will solve your problems too.

I'll keep you posted, thanks.

**Comment by bfeher** [comment]
I updated the pod of **BFRadialWaveHUD** to version `1.5.4` which now explicitly states the version of **BFRadialWaveView**.

I created a new project and used this podfile:
`pod 'BFRadialWaveHUD', '~> 1.5.4'`
and everything seems to be working perfectly. Perhaps you could update to this and give it a go?

Thanks!

**Comment by natalia-osa** [comment]
Hi again,

Here is the .podspec file, I was referring to: https://github.com/CocoaPods/Specs/blob/master/Specs/BFRadialWaveHUD/1.5.4/BFRadialWaveHUD.podspec.json and there are the lines I was quoting.

I've installed version 1.5.4 and everything is working correctly. I can see all the newest methods. 

Thanks :)

**Comment by bfeher** [comment]
Glad to hear. Thanks for your input :)
